
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVER = 10;
  public static final int CADENA = 21;
  public static final int LETRA = 18;
  public static final int LLAVEL = 9;
  public static final int SIGNO = 17;
  public static final int ASIGN = 4;
  public static final int SEPA = 3;
  public static final int ID = 20;
  public static final int POR = 14;
  public static final int COMA = 8;
  public static final int EOF = 0;
  public static final int DISYUN = 11;
  public static final int DIGITO = 16;
  public static final int VIRGU = 15;
  public static final int CONJ = 2;
  public static final int error = 1;
  public static final int DOT = 7;
  public static final int DDOT = 6;
  public static final int SINTER = 12;
  public static final int ESPE = 19;
  public static final int MAS = 13;
  public static final int PTCOMA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "SEPA",
  "ASIGN",
  "PTCOMA",
  "DDOT",
  "DOT",
  "COMA",
  "LLAVEL",
  "LLAVER",
  "DISYUN",
  "SINTER",
  "MAS",
  "POR",
  "VIRGU",
  "DIGITO",
  "SIGNO",
  "LETRA",
  "ESPE",
  "ID",
  "CADENA"
  };
}

